version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: procontext_php
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - procontext
  nginx:
    image: nginx:latest
    container_name: procontext_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - procontext
  mysql:
    image: mysql:latest
    container_name: procontext_mysql
    restart: always
    volumes:
      - ../storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - procontext
networks:
  procontext:
    driver: bridge