version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: egeland_php
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:latest
    container_name: egeland_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  kemorial:
    image: mysql:latest
    container_name: egeland_mysql
    restart: always
    volumes:
      - ../storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root